# This file was automagically generated by mbed.org. For more information, 
# see http://mbed.org/handbook/Exporting-to-GCC-ARM-Embedded

GCC_BIN = 
PROJECT = OwnTracksPrime
OBJECTS = ./MQTT/MQTTPacket/MQTTConnectClient.o ./MQTT/MQTTPacket/MQTTConnectServer.o ./MQTT/MQTTPacket/MQTTDeserializePublish.o ./MQTT/MQTTPacket/MQTTPacket.o ./MQTT/MQTTPacket/MQTTSerializePublish.o ./MQTT/MQTTPacket/MQTTSubscribeClient.o ./MQTT/MQTTPacket/MQTTSubscribeServer.o ./MQTT/MQTTPacket/MQTTUnsubscribeClient.o ./MQTT/MQTTPacket/MQTTUnsubscribeServer.o ./main.o ./C027_Support/GPS.o ./C027_Support/MDM.o ./C027_Support/SerialPipe.o 
SYS_OBJECTS = ./mbed/TARGET_UBLOX_C027/TOOLCHAIN_GCC_ARM/board.o ./mbed/TARGET_UBLOX_C027/TOOLCHAIN_GCC_ARM/cmsis_nvic.o ./mbed/TARGET_UBLOX_C027/TOOLCHAIN_GCC_ARM/mbed_overrides.o ./mbed/TARGET_UBLOX_C027/TOOLCHAIN_GCC_ARM/retarget.o ./mbed/TARGET_UBLOX_C027/TOOLCHAIN_GCC_ARM/startup_LPC17xx.o ./mbed/TARGET_UBLOX_C027/TOOLCHAIN_GCC_ARM/system_LPC17xx.o 
INCLUDE_PATHS = -I. -I./C027_Support -I./C027_Support/Socket -I./MQTT -I./MQTT/FP -I./MQTT/MQTTPacket -I./mbed -I./mbed/TARGET_UBLOX_C027 -I./mbed/TARGET_UBLOX_C027/TARGET_NXP -I./mbed/TARGET_UBLOX_C027/TARGET_NXP/TARGET_LPC176X -I./mbed/TARGET_UBLOX_C027/TARGET_NXP/TARGET_LPC176X/TARGET_UBLOX_C027 -I./mbed/TARGET_UBLOX_C027/TOOLCHAIN_GCC_ARM 
LIBRARY_PATHS = -L./mbed/TARGET_UBLOX_C027/TOOLCHAIN_GCC_ARM 
LIBRARIES = -lmbed 
LINKER_SCRIPT = ./mbed/TARGET_UBLOX_C027/TOOLCHAIN_GCC_ARM/LPC1768.ld

############################################################################### 
AS      = $(GCC_BIN)arm-none-eabi-as
CC      = $(GCC_BIN)arm-none-eabi-gcc
CPP     = $(GCC_BIN)arm-none-eabi-g++
LD      = $(GCC_BIN)arm-none-eabi-gcc
OBJCOPY = $(GCC_BIN)arm-none-eabi-objcopy
OBJDUMP = $(GCC_BIN)arm-none-eabi-objdump
SIZE    = $(GCC_BIN)arm-none-eabi-size 


CPU = -mcpu=cortex-m3 -mthumb 
CC_FLAGS = $(CPU) -c -g -fno-common -fmessage-length=0 -Wall -Wextra -fno-exceptions -ffunction-sections -fdata-sections -fomit-frame-pointer -MMD -MP
CC_SYMBOLS = -DTARGET_FF_ARDUINO -DTOOLCHAIN_GCC_ARM -DTOOLCHAIN_GCC -DTARGET_LIKE_CORTEX_M3 -DTARGET_CORTEX_M -DTARGET_LIKE_MBED -DTARGET_LPC176X -DTARGET_NXP -DARM_MATH_CM3 -DTARGET_LPC1768 -D__CORTEX_M3 -DTARGET_UBLOX_C027 -DTARGET_M3 -D__MBED__=1 -DMBED_BUILD_TIMESTAMP=1460983076.32 

LD_FLAGS = $(CPU) -Wl,--gc-sections --specs=nano.specs -u _printf_float -u _scanf_float -Wl,--wrap,main -Wl,-Map=$(PROJECT).map,--cref
LD_SYS_LIBS = -lstdc++ -lsupc++ -lm -lc -lgcc -lnosys


ifeq ($(DEBUG), 1)
  CC_FLAGS += -DDEBUG -O0
else
  CC_FLAGS += -DNDEBUG -Os
endif

.PHONY: all clean lst size

all: $(PROJECT).bin $(PROJECT).hex size


clean:
	rm -f $(PROJECT).bin $(PROJECT).elf $(PROJECT).hex $(PROJECT).map $(PROJECT).lst $(OBJECTS) $(DEPS)


.asm.o:
	$(CC) $(CPU) -c -x assembler-with-cpp -o $@ $<
.s.o:
	$(CC) $(CPU) -c -x assembler-with-cpp -o $@ $<
.S.o:
	$(CC) $(CPU) -c -x assembler-with-cpp -o $@ $<

.c.o:
	$(CC)  $(CC_FLAGS) $(CC_SYMBOLS) -std=gnu99   $(INCLUDE_PATHS) -o $@ $<

.cpp.o:
	$(CPP) $(CC_FLAGS) $(CC_SYMBOLS) -std=gnu++98 -fno-rtti $(INCLUDE_PATHS) -o $@ $<



$(PROJECT).elf: $(OBJECTS) $(SYS_OBJECTS)
	$(LD) $(LD_FLAGS) -T$(LINKER_SCRIPT) $(LIBRARY_PATHS) -o $@ $^ $(LIBRARIES) $(LD_SYS_LIBS) $(LIBRARIES) $(LD_SYS_LIBS)


$(PROJECT).bin: $(PROJECT).elf
	$(OBJCOPY) -O binary $< $@

$(PROJECT).hex: $(PROJECT).elf
	@$(OBJCOPY) -O ihex $< $@

$(PROJECT).lst: $(PROJECT).elf
	@$(OBJDUMP) -Sdh $< > $@

lst: $(PROJECT).lst

size: $(PROJECT).elf
	$(SIZE) $(PROJECT).elf

DEPS = $(OBJECTS:.o=.d) $(SYS_OBJECTS:.o=.d)
-include $(DEPS)


